"""first commit

Revision ID: 795a443bd65d
Revises: 
Create Date: 2024-03-09 13:42:24.878612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '795a443bd65d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stiglers',
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('commodity', sa.String(length=32), nullable=False),
    sa.Column('unit', sa.String(length=12), nullable=False),
    sa.Column('price_cents', sa.Numeric(precision=3, scale=1), nullable=False),
    sa.Column('calories', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.Column('protein_g', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.Column('calcium_g', sa.Numeric(precision=16, scale=4), nullable=False),
    sa.Column('iron_mg', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.Column('vitamin_a_iu', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.Column('vitamin_b1_mg', sa.Numeric(precision=3, scale=1), nullable=False),
    sa.Column('vitamin_b2_mg', sa.Numeric(precision=3, scale=1), nullable=False),
    sa.Column('niacin_mg', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.Column('vitamin_c_mg', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.PrimaryKeyConstraint('idx', name=op.f('pk_stiglers'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stiglers')
    # ### end Alembic commands ###
