name: Simple update scheduling


on:
  push:
    branches:
      - "action**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
        cache: 'pip'
    - name: Pip audit action
      uses: pypa/gh-action-pip-audit@v1.0.8
      with:
        inputs: requirements.txt dev-requirements.txt
    - name: Intstall dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r dev-requirements.txt
    - name: Run pur
      run: |
        python -m pur -r requirements.txt --skip pydantic-core,starlette
        python -m pip install -r requirements.txt
