name: Simple update scheduling


on:
  schedule:
    - cron: "1 0 * * 0"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Intstall dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r dev-requirements.txt
    - name: Run pur
      run: |
        python -m pur -r requirements.txt --skip starlette
        python -m pip install -r requirements.txt
